#!/usr/bin/env bash

##########
# Git Pre-Commit file for PHP projects.
###
#
# Modified from Allyson Silva's pre-commit script
#
# This hook performs the following validation:
#   - PHP Lint (http://php.net/manual/en/features.commandline.options.php)
#
# @version 1.0.2
# @author Shawn Rice <zooley@purdue.edu>
# @author Allyson Silva <allysonsilvaweb@gmail.com>
##########

    cat <<\EOF

    ____                                                 _ __
   / __ \________        _________  ____ ___  ____ ___  (_) /_
  / /_/ / ___/ _ \______/ ___/ __ \/ __ `__ \/ __ `__ \/ / __/
 / ____/ /  /  __/_____/ /__/ /_/ / / / / / / / / / / / / /_
/_/   /_/   \___/      \___/\____/_/ /_/ /_/_/ /_/ /_/_/\__/
EOF

echo

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
    # Note that the use of brackets around a tr range is ok here, (it's
    # even required, for portability to Solaris 10's /usr/bin/tr), since
    # the square bracket bytes happen to fall in the designated range.
    test $(git diff --cached --name-only --diff-filter=A -z $against |
      LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
    cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
    exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
# exec git diff-index --check --cached $against --

#################
# Terminal Colors
#################

###
# Regular
###
color_regular_black='\033[0;30m'
color_regular_red='\033[0;31m'
color_regular_green='\033[0;32m'
color_regular_yellow='\033[0;33m'
color_regular_blue='\033[0;34m'
color_regular_purple='\033[0;35m'
color_regular_cyan='\033[0;36m'
color_regular_white='\033[0;37m'

###
# Bold
###
color_bold_black='\033[1;30m'
color_bold_red='\033[1;31m'
color_bold_green='\033[1;32m'
color_bold_yellow='\033[1;33m'
color_bold_blue='\033[1;34m'
color_bold_purple='\033[1;35m'
color_bold_cyan='\033[1;36m'
color_bold_white='\033[1;37m'

###
# Underline
###
color_underline_black='\033[4;30m'
color_underline_red='\033[4;31m'
color_underline_green='\033[4;32m'
color_underline_yellow='\033[4;33m'
color_underline_blue='\033[4;34m'
color_underline_purple='\033[4;35m'
color_underline_cyan='\033[4;36m'
color_underline_white='\033[4;37m'

###
# Background
###
color_background_black='\033[40m'
color_background_red='\033[41m'
color_background_green='\033[42m'
color_background_yellow='\033[43m'
color_background_blue='\033[44m'
color_background_purple='\033[45m'
color_background_cyan='\033[46m'
color_background_white='\033[47m'

color_reset='\033[0m'

###########
# Functions
###########

function message_failure() {
    printf "${color_bold_white}${color_background_red} $1 ${color_reset}\n"
}

function message_success() {
    printf "${color_bold_black}${color_background_green} $1 ${color_reset}\n"
}

function message_warning() {
    printf "${color_bold_black}${color_background_yellow} $1 ${color_reset}\n"
}

function message_info() {
    printf "${color_bold_black}${color_background_blue} $1 ${color_reset}\n"
}

######################
# Checking PHP Project
######################

# Exit 0 if no errors found
# Exit 1 if errors were found

# Create empty errors array.
declare -a errors

# Fetch all changed php files and validate them.
# This will check only staged files to be commited.
files=$(git diff --name-only --diff-filter=ACM HEAD^ | grep '\.php$' | grep -Ev '\.(blade.php|txt)$' | grep -Ev '(_ide_helper.php)$')
echo "Files:"
for file in $files
do
    echo "    ${file}"
done

# Project Folder.
project=$(git rev-parse --show-toplevel)
echo "Project:"
echo "    ${project}"
echo

# Apenas caminhos e nomes dos arquivos: /path/file.php,/foo/file.php,/bar/file.php
for relative_file_path in $files
do
    staged_files="$staged_files $(git rev-parse --show-toplevel)/$relative_file_path"
    # file_name=$(basename "$relative_file_path")
    # file_entension=${file_name##*.}
done

# Replace first blank only
staged_files=${staged_files/ /''}

# Separated by spaces
staged_files_separated_by_spaces=$staged_files

# Remove blank spaces with comma
# Separated by commas
staged_files_separated_by_comma=${staged_files// /,}

if [ -n "$files" ]; then
    echo "|-----------------------------------|"
    printf "|       ${color_bold_white}Checking PHP Lint...${color_reset}        |\n"
    echo "|-----------------------------------|"
    echo

    # Check for errors when running PHP LINT.
    php_lint_errors=false

    for file in $files; do

        # Check if they are valid php files.
        php_lint_output=`php -l -d display_errors=On $file 2>&1 | grep 'Parse error:'`

        # If it did contain errors, we have output.
        if [ -n "$php_lint_output" ]; then
            # Printing error message.
            message_failure "$php_lint_output"

            # Adding error message.
            errors=("${errors[@]}" "$php_lint_output")

            php_lint_errors=true
        fi
    done

    if [ "$php_lint_errors" = false ]; then
        message_success 'No Errors Found - PHP Lint(Syntax check only)'
    else
        exit 1
    fi
fi

echo

# If we have errors, exit with 1
if [ -n "$errors" ]; then
    message_failure 'Please check the terminal output and solve the errors!'
    exit 1
fi

message_success 'No Errors Found.'

exit 0
