<?php
/**
 * @package    halcyon
 * @copyright  Copyright 2020 Purdue University.
 * @license    http://opensource.org/licenses/MIT MIT
 */

return [
	'widget name' => 'Google Analytics',
	'widget desc' => 'This module adds some Javascript to the page for Google Analytics reporting',
	// Parameters
	'api key' => 'API Key',
	'api key description' => 'An API key generated by Google',
];
