<?php

return [
	'widget name' => 'Google Analytics',
	'widget desc' => 'This module adds some Javascript to the page for Google Analytics reporting',
	// Parameters
	'api key' => 'API Key',
	'api key description' => 'An API key generated by Google',
	'service' => 'Google Service',
	'service description' => 'Which Google Analytics service to use.',
];
