<?php

use App\Listeners\Listeners\Activators\FileActivator;
use App\Listeners\Listeners\Activators\DatabaseActivator;

return [

	/*
	|--------------------------------------------------------------------------
	| Listener Namespace
	|--------------------------------------------------------------------------
	|
	| Default module namespace.
	|
	*/
	'namespace' => 'App\\Listeners',

	/*
	|--------------------------------------------------------------------------
	| Listener Stubs
	|--------------------------------------------------------------------------
	|
	| Default module stubs.
	|
	*/
	'stubs' => [
		'enabled' => false,
		'path' => base_path() . '/vendor/nwidart/laravel-modules/src/Commands/stubs',
		'files' => [
			'routes/web' => 'Routes/web.php',
			'routes/api' => 'Routes/api.php',
			'views/index' => 'Resources/views/index.blade.php',
			'views/master' => 'Resources/views/layouts/master.blade.php',
			'scaffold/config' => 'Config/config.php',
			'composer' => 'composer.json',
			'assets/js/app' => 'Resources/assets/js/app.js',
			'assets/sass/app' => 'Resources/assets/sass/app.scss',
			'webpack' => 'webpack.mix.js',
			'package' => 'package.json',
		],
		'replacements' => [
			'routes/web' => ['LOWER_NAME', 'STUDLY_NAME'],
			'routes/api' => ['LOWER_NAME'],
			'webpack' => ['LOWER_NAME'],
			'json' => ['LOWER_NAME', 'STUDLY_NAME', 'MODULE_NAMESPACE', 'PROVIDER_NAMESPACE'],
			'views/index' => ['LOWER_NAME'],
			'views/master' => ['LOWER_NAME', 'STUDLY_NAME'],
			'scaffold/config' => ['STUDLY_NAME'],
			'composer' => [
				'LOWER_NAME',
				'STUDLY_NAME',
				'VENDOR',
				'AUTHOR_NAME',
				'AUTHOR_EMAIL',
				'MODULE_NAMESPACE',
				'PROVIDER_NAMESPACE',
			],
		],
		'gitkeep' => true,
	],

	'paths' => [
		/*
		|--------------------------------------------------------------------------
		| Listeners path
		|--------------------------------------------------------------------------
		|
		| This path used for save the generated listener. This path also will be
		| added automatically to list of scanned folders.
		|
		*/
		'listeners' => app_path('Listeners'),

		/*
		|--------------------------------------------------------------------------
		| Listeners assets path
		|--------------------------------------------------------------------------
		|
		| Here you may update the listeners assets path.
		|
		*/
		'assets' => public_path('listeners'),

		/*
		|--------------------------------------------------------------------------
		| The migrations path
		|--------------------------------------------------------------------------
		|
		| Where you run 'listener:publish-migration' command, where do you publish
		| the migration files?
		|
		*/
		'migration' => base_path('database/migrations'),

		/*
		|--------------------------------------------------------------------------
		| Generator path
		|--------------------------------------------------------------------------
		| Customise the paths where the folders will be generated.
		| Set the generate key to false to not generate that folder
		*/
		'generator' => [
			'config' => ['path' => 'Config', 'generate' => true],
			'command' => ['path' => 'Console', 'generate' => true],
			'migration' => ['path' => 'Database/Migrations', 'generate' => true],
			'seeder' => ['path' => 'Database/Seeders', 'generate' => true],
			'factory' => ['path' => 'Database/factories', 'generate' => true],
			'model' => ['path' => 'Entities', 'generate' => true],
			'assets' => ['path' => 'Resources/assets', 'generate' => true],
			'lang' => ['path' => 'Resources/lang', 'generate' => true],
			'views' => ['path' => 'Resources/views', 'generate' => true],
			'test' => ['path' => 'Tests/Unit', 'generate' => true],
			'repository' => ['path' => 'Repositories', 'generate' => false],
		],
	],

	/*
	|--------------------------------------------------------------------------
	| Scan Path
	|--------------------------------------------------------------------------
	|
	| Here you define which folder will be scanned. By default will scan vendor
	| directory. This is useful if you host the package in packagist website.
	|
	*/
	'scan' => [
		'enabled' => false,
		'paths' => [
			base_path('vendor/*/*'),
		],
	],

	/*
	|--------------------------------------------------------------------------
	| Composer File Template
	|--------------------------------------------------------------------------
	|
	| Here is the config for composer.json file, generated by this package
	|
	*/
	'composer' => [
		'vendor' => 'rcac',
		'author' => [
			'name' => 'Research Computing at Purdue',
			'email' => 'support@purdue.edu',
		],
	],

	/*
	|--------------------------------------------------------------------------
	| Caching
	|--------------------------------------------------------------------------
	|
	| Here is the config for setting up caching feature.
	|
	*/
	'cache' => [
		'enabled' => false,
		'key' => 'laravel-listeners',
		'lifetime' => 60,
	],

	/*
	|--------------------------------------------------------------------------
	| Choose what laravel-modules will register as custom namespaces.
	| Setting one to false will require you to register that part
	| in your own Service Provider class.
	|--------------------------------------------------------------------------
	*/
	'register' => [
		'translations' => true,
		/**
		 * load files on boot or register method
		 *
		 * Note: boot not compatible with asgardcms
		 *
		 * @example boot|register
		 */
		'files' => 'register',
	],

	/*
	|--------------------------------------------------------------------------
	| Activators
	|--------------------------------------------------------------------------
	|
	| You can define new types of activators here, file, database etc. The only
	| required parameter is 'class'.
	| The file activator will store the activation status in storage/installed_modules
	*/
	'activators' => [
		'file' => [
			'class' => FileActivator::class,
			'statuses-file' => base_path('listeners_statuses.json'),
			'cache-key' => 'activator.installed',
			'cache-lifetime' => 604800,
		],
		'database' => [
			'class' => DatabaseActivator::class,
			'cache-key' => 'activator.installed',
			'cache-lifetime' => 604800,
		],
	],

	'activator' => 'database',
];
